name: Build and Release

on:
  push:
    tags:
      - "v*"

env:
  PLUGIN_NAME: logseq-export-block

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Prepare plugin package
        id: build
        run: |
          mkdir -p ${{ env.PLUGIN_NAME }}
          cp -rf README.md package.json logseq_export_block_logo.png LICENSE dist/ ${{ env.PLUGIN_NAME }}/
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          echo "tag_name=$(git tag --sort version:refname | tail -n 1)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          draft: false
          prerelease: false

      - name: Upload zip file
        id: upload_zip
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ env.PLUGIN_NAME }}.zip
          name: ${{ env.PLUGIN_NAME }}-${{ steps.build.outputs.tag_name }}
